export const UNAUTHORIZED_ERROR_CODE = 'UNAUTHORIZED';
export const TOO_MANY_REQUESTS_ERROR_CODE = 'TOO_MANY_REQUESTS';
export const TOO_MANY_REQUESTS_ERROR_MESSAGE = 'Too many requests';
export const CONFLICT_ERROR_CODE = 'CONFLICT';
export const NOT_FOUND_ERROR_CODE = 'NOT_FOUND';
export const BAD_REQUEST_ERROR_CODE = 'BAD_REQUEST';
